// <auto-generated />
using System;
using Labb1_MinimalAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb1_MinimalAPI.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20230918122032_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb1_MinimalAPI.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("783c8e49-e992-46f5-922a-7d1528c4c4fd"),
                            Author = "George R. R. Martin",
                            Description = "A Game of Thrones is the first novel in A Song of Ice and Fire",
                            Genre = "Political Fiction",
                            Title = "A Game of Thrones",
                            Year = "1996",
                            isAvailable = true
                        },
                        new
                        {
                            Id = new Guid("43f039ab-5585-4042-b0ec-b7fe32d6b47a"),
                            Author = "George R. R. Martin",
                            Description = "A Clash of Kings is the second of seven planned novels in A Song of Ice and Fire",
                            Genre = "Political Fiction",
                            Title = "A Clash of Kings",
                            Year = "1998",
                            isAvailable = true
                        },
                        new
                        {
                            Id = new Guid("2cf1dd5f-d543-41cd-83ef-6ff723e27c4b"),
                            Author = "George R. R. Martin",
                            Description = "A Storm of Swords is the third of seven planned novels in A Song of Ice and Fire",
                            Genre = "Political Fiction",
                            Title = "A Storm of Swords",
                            Year = "2000",
                            isAvailable = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
